// ----------------------------------------------------------------------
// GENERATED USING VERCEL v0
// The following components (Testimonials, Pricing) utilize patterns 
// typically generated by v0 (Card-based, heavily utilizing utility classes).
// ----------------------------------------------------------------------


import { 
  CheckCircle2, 
} from 'lucide-react';

import { Button } from './Button';
export const Pricing = () => {
  // Generated using Vercel v0
  return (
    <section className="w-full py-20 bg-slate-50">
      <div className="container mx-auto px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Simple, Transparent Pricing</h2>
            <p className="max-w-[900px] text-slate-500 md:text-xl/relaxed">
              Start for free, scale when you need to. No hidden fees.
            </p>
          </div>
        </div>
        <div className="grid grid-cols-1 gap-6 pt-12 md:grid-cols-3 lg:gap-8 max-w-6xl mx-auto">
          
          {/* Free Tier */}
          <div className="flex flex-col rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <div className="space-y-2">
              <h3 className="text-2xl font-bold text-slate-900">Starter</h3>
              <p className="text-slate-500">For individuals and hobbyists.</p>
            </div>
            <div className="mt-4 flex items-baseline text-slate-900">
              <span className="text-4xl font-extrabold tracking-tight">$0</span>
              <span className="ml-1 text-xl font-semibold text-slate-500">/mo</span>
            </div>
            <ul className="mt-6 space-y-4 flex-1">
              {['Up to 3 projects', 'Basic analytics', '1 Team member', 'Community support'].map((feature) => (
                <li key={feature} className="flex items-center text-slate-600">
                  <CheckCircle2 className="mr-2 h-4 w-4 text-indigo-600" />
                  {feature}
                </li>
              ))}
            </ul>
            <div className="mt-8">
              <Button variant="outline" className="w-full">Get Started</Button>
            </div>
          </div>

          {/* Pro Tier (Highlighted) */}
          <div className="relative flex flex-col rounded-2xl border-2 border-indigo-600 bg-white p-6 shadow-xl scale-105 z-10">
            <div className="absolute -top-4 left-0 right-0 mx-auto w-fit rounded-full bg-indigo-600 px-3 py-1 text-xs font-medium text-white">
              Most Popular
            </div>
            <div className="space-y-2">
              <h3 className="text-2xl font-bold text-slate-900">Pro</h3>
              <p className="text-slate-500">For growing teams.</p>
            </div>
            <div className="mt-4 flex items-baseline text-slate-900">
              <span className="text-4xl font-extrabold tracking-tight">$29</span>
              <span className="ml-1 text-xl font-semibold text-slate-500">/mo</span>
            </div>
            <ul className="mt-6 space-y-4 flex-1">
              {['Unlimited projects', 'Advanced analytics', 'Up to 10 team members', 'Priority support', 'Slack Integration'].map((feature) => (
                <li key={feature} className="flex items-center text-slate-600">
                  <CheckCircle2 className="mr-2 h-4 w-4 text-indigo-600" />
                  {feature}
                </li>
              ))}
            </ul>
            <div className="mt-8">
              <Button className="w-full">Start Free Trial</Button>
            </div>
          </div>

          {/* Enterprise Tier */}
          <div className="flex flex-col rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <div className="space-y-2">
              <h3 className="text-2xl font-bold text-slate-900">Enterprise</h3>
              <p className="text-slate-500">For large organizations.</p>
            </div>
            <div className="mt-4 flex items-baseline text-slate-900">
              <span className="text-4xl font-extrabold tracking-tight">Custom</span>
            </div>
            <ul className="mt-6 space-y-4 flex-1">
              {['Unlimited everything', 'SSO & Security', 'Dedicated account manager', 'Custom contracts', '24/7 Phone support'].map((feature) => (
                <li key={feature} className="flex items-center text-slate-600">
                  <CheckCircle2 className="mr-2 h-4 w-4 text-indigo-600" />
                  {feature}
                </li>
              ))}
            </ul>
            <div className="mt-8">
              <Button variant="outline" className="w-full">Contact Sales</Button>
            </div>
          </div>

        </div>
      </div>
    </section>
  );
};
