// ----------------------------------------------------------------------
// GENERATED USING VERCEL v0
// The following components (Testimonials, Pricing) utilize patterns 
// typically generated by v0 (Card-based, heavily utilizing utility classes).
// ----------------------------------------------------------------------


import { 
  Star
} from 'lucide-react';

export const Testimonials = () => {
  // Generated using Vercel v0
  return (
    <section className="w-full py-20 bg-white">
      <div className="container mx-auto px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Trusted by 4,000+ Teams</h2>
            <p className="max-w-[900px] text-slate-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Don&apos;t take our word for it. Here is what our community has to say.
            </p>
          </div>
        </div>
        <div className="mx-auto grid max-w-5xl grid-cols-1 gap-6 py-12 md:grid-cols-2 lg:grid-cols-3">
          
          {/* Card 1 */}
          <div className="flex flex-col justify-between rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
            <div className="space-y-4">
              <div className="flex space-x-1">
                {[...Array(5)].map((_, i) => (
                  <Star key={i} className="h-4 w-4 fill-amber-400 text-amber-400" />
                ))}
              </div>
              <p className="text-slate-600">
                "TaskFlow has completely transformed how our engineering team operates. The clarity it provides is unmatched."
              </p>
            </div>
            <div className="mt-6 flex items-center space-x-3">
              <div className="h-10 w-10 rounded-full bg-slate-200 flex items-center justify-center text-slate-500 font-bold">JD</div>
              <div>
                <p className="text-sm font-semibold text-slate-900">John Doe</p>
                <p className="text-xs text-slate-500">CTO at TechCorp</p>
              </div>
            </div>
          </div>

          {/* Card 2 */}
          <div className="flex flex-col justify-between rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
            <div className="space-y-4">
              <div className="flex space-x-1">
                {[...Array(5)].map((_, i) => (
                  <Star key={i} className="h-4 w-4 fill-amber-400 text-amber-400" />
                ))}
              </div>
              <p className="text-slate-600">
                Simple enough for our marketing team, powerful enough for our devs. The perfect balance."
              </p>
            </div>
            <div className="mt-6 flex items-center space-x-3">
              <div className="h-10 w-10 rounded-full bg-slate-200 flex items-center justify-center text-slate-500 font-bold">JS</div>
              <div>
                <p className="text-sm font-semibold text-slate-900">Jane Smith</p>
                <p className="text-xs text-slate-500">VP Marketing</p>
              </div>
            </div>
          </div>

          {/* Card 3 */}
          <div className="flex flex-col justify-between rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
            <div className="space-y-4">
              <div className="flex space-x-1">
                {[...Array(5)].map((_, i) => (
                  <Star key={i} className="h-4 w-4 fill-amber-400 text-amber-400" />
                ))}
              </div>
              <p className="text-slate-600">
                I&apos;ve tried Asana, Jira, and Monday. TaskFlow is the only one that didn't feel like a second job to maintain."
              </p>
            </div>
            <div className="mt-6 flex items-center space-x-3">
              <div className="h-10 w-10 rounded-full bg-slate-200 flex items-center justify-center text-slate-500 font-bold">MK</div>
              <div>
                <p className="text-sm font-semibold text-slate-900">Mike King</p>
                <p className="text-xs text-slate-500">Product Manager</p>
              </div>
            </div>
          </div>

        </div>
      </div>
    </section>
  );
};